apiVersion: apps/v1
kind: Deployment
metadata:
  name: haystack-rag-gateway-api-gw
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/instance: haystack-rag
    app.kubernetes.io/component: api-gw
    app.kubernetes.io/group: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haystack-rag
      app.kubernetes.io/component: api-gw
      app.kubernetes.io/group: gateway
  template:
    metadata:
      labels:
        app: haystack-rag
        app.kubernetes.io/component: api-gw
        app.kubernetes.io/group: gateway
    spec:
      containers:
      - name: traefik
        image: "traefik:v2.10"
        args:
          - "--providers.file.directory=/etc/traefik/conf.d"
          - "--providers.file.watch=true"
          - "--entrypoints.web.address=:8080"
          - "--entrypoints.traefik.address=:8081"
          - "--api.insecure=true"
          - "--log.level=DEBUG"
          - "--ping"
        ports:
          - name: web
            containerPort: 8080
          - name: traefik
            containerPort: 8081
        volumeMounts:
          - name: config
            mountPath: /etc/traefik/conf.d
            readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: haystack-rag-gateway-api-gw-config
