apiVersion: v1
kind: Service
metadata:
  name: haystack-rag-api-gw
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/component: api-gw
    app.kubernetes.io/group: gateway
spec:
  type: NodePort
  selector:
    app: haystack-rag
    app.kubernetes.io/component: api-gw
    app.kubernetes.io/group: gateway
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 32080
    - name: traefik
      port: 8081
      targetPort: 8081
      nodePort: 32081
