apiVersion: v1
kind: Secret
metadata:
  name: haystack-rag-secrets
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/instance: haystack-rag
type: Opaque
stringData:
  opensearch-user: ${OPENSEARCH_USER}
  opensearch-password: ${OPENSEARCH_PASSWORD}
  openai-key: ${OPENAI_KEY}
