apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ default "rag-local-tls" .Values.certificate.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ default "rag-local-tls" .Values.certificate.secretName }}
  commonName: {{ default "rag.local" .Values.certificate.commonName }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    name: {{ default "selfsigned-cluster-issuer" .Values.certificate.issuer.name }}
    kind: {{ default "ClusterIssuer" .Values.certificate.issuer.kind }}
