apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-frontend-config
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/group: frontend
  {{- include "charts.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.frontendConfig.nginxConf | toYaml | indent 1 }}
