apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-gateway-api-gw-config
  labels:
    app.kubernetes.io/component: api-gw
    app.kubernetes.io/group: gateway
    app: {{ include "charts.fullname" . }}
  {{- include "charts.labels" . | nindent 4 }}
data:
  traefik.yml: |-
{{ tpl (index .Values.gatewayApiGwConfig "traefik.yml") . | indent 4 }}
