apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-frontend-config
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/group: frontend
  {{- include "charts.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.frontendConfig.nginxConf | toYaml | indent 1 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/group: frontend
  {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: haystack-rag
      app.kubernetes.io/component: frontend
      app.kubernetes.io/group: frontend
    {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: haystack-rag
        app.kubernetes.io/component: frontend
        app.kubernetes.io/group: frontend
      {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.frontend.frontend.image.repository }}:{{ .Values.frontend.frontend.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.frontend.frontend.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: react-app
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: frontend
        ports:
        - containerPort: 3000
          name: react-app
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: react-app
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources: {{- toYaml .Values.frontend.frontend.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: config
          readOnly: true
          subPath: nginx.conf
      volumes:
      - configMap:
          name: {{ include "charts.fullname" . }}-frontend-config
        name: config
