apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "charts.fullname" . }}-haystack-rag
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  ingressClassName: traefik
  rules:
  - host: rag.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "charts.fullname" . }}-api-gw
            port:
              number: 8080
