apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "charts.fullname" . }}-frontend-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.frontendIngress.host | default "rag.local" }}
      secretName: {{ .Values.frontendIngress.tlsSecret | default "rag-local-tls" }}
  rules:
    - host: {{ .Values.frontendIngress.host | default "rag.local" }}
      http:
        paths:
          - path: {{ .Values.frontendIngress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontendIngress.serviceName | default "haystack-rag-frontend" }}
                port:
                  number: {{ .Values.frontendIngress.servicePort | default 3000 }}
