# Default deny all ingress and egress traffic for all pods in the namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# Allow traffic for pods labeled with "app: <fullname>" only from pods with the label "access: allowed"
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-haystack-traffic
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "charts.fullname" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: allowed
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "charts.fullname" . }}
