apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "charts.fullname" . }}-file-storage
  labels:
    app.kubernetes.io/group: backend
  {{- include "charts.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.fileStorage.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.fileStorage.storageClass | quote }}
