apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-secrets
  labels:
  {{- include "charts.labels" . | nindent 4 }}
data:
  openai-api-key: {{ required "secrets.openaiApiKey is required" .Values.secrets.openaiApiKey
    | b64enc | quote }}
  opensearch-password: {{ required "secrets.opensearchPassword is required" .Values.secrets.opensearchPassword
    | b64enc | quote }}
  opensearch-user: {{ required "secrets.opensearchUser is required" .Values.secrets.opensearchUser
    | b64enc | quote }}
type: Opaque
