apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-secrets
  labels:
    app: {{ include "charts.fullname" . }}
    {{- include "charts.labels" . | nindent 4 }}
type: Opaque
stringData:
  openai-api-key: {{ .Values.secrets.openaiApiKey | required "secrets.openaiApiKey is required" | trim | quote }}
  opensearch-password: {{ .Values.secrets.opensearchPassword | required "secrets.opensearchPassword is required" | trim | quote }}
  opensearch-user: {{ .Values.secrets.opensearchUser | required "secrets.opensearchUser is required" | trim | quote }}
