apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/group: frontend
    app: {{ include "charts.fullname" . }}
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.type }}
  selector:
    app: {{ include "charts.fullname" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/group: frontend
    {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.frontend.ports | toYaml | nindent 2 }}
