apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-api-gw
  labels:
    app.kubernetes.io/component: api-gw
    app.kubernetes.io/group: gateway
    app: {{ include "charts.fullname" . }}
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGw.type }}
  selector:
    app: {{ include "charts.fullname" . }}
    app.kubernetes.io/component: api-gw
    app.kubernetes.io/group: gateway
    {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
  {{- toYaml .Values.apiGw.ports | nindent 2 }}
