apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-opensearch
  labels:
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/group: search
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "charts.fullname" . }}
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opensearch.type }}
  selector:
    app: {{ include "charts.fullname" . }}
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/group: search
  ports:
  {{- .Values.opensearch.ports | toYaml | nindent 2 }}
