apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "charts.fullname" . }}-search-opensearch
  labels:
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/group: search
    app: {{ include "charts.fullname" . }}
  {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.searchOpensearch.replicas }}
  selector:
    matchLabels:
      app: {{ include "charts.fullname" . }}
      app.kubernetes.io/component: opensearch
      app.kubernetes.io/group: search
  serviceName: {{ include "charts.fullname" . }}-opensearch
  template:
    metadata:
      labels:
        app: {{ include "charts.fullname" . }}
        app.kubernetes.io/component: opensearch
        app.kubernetes.io/group: search
    spec:
      containers:
      - env:
        - name: discovery.type
          value: {{ quote .Values.searchOpensearch.opensearch.env.discoveryType }}
        - name: bootstrap.memory_lock
          value: {{ quote .Values.searchOpensearch.opensearch.env.bootstrapMemoryLock }}
        - name: OPENSEARCH_JAVA_OPTS
          value: {{ quote .Values.searchOpensearch.opensearch.env.opensearchJavaOpts }}
        - name: OPENSEARCH_SECURITY_ENABLED
          value: {{ quote .Values.searchOpensearch.opensearch.env.opensearchSecurityEnabled }}
        - name: OPENSEARCH_INITIAL_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: opensearch-user
              name: {{ include "charts.fullname" . }}-secrets
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: opensearch-password
              name: {{ include "charts.fullname" . }}-secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.searchOpensearch.opensearch.image.repository }}:{{ .Values.searchOpensearch.opensearch.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.searchOpensearch.opensearch.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 180
          periodSeconds: 10
          tcpSocket:
            port: 9200
          timeoutSeconds: 5
        name: opensearch
        ports:
        - containerPort: 9200
          name: rest-api
        - containerPort: 9600
          name: performance
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 90
          periodSeconds: 10
          tcpSocket:
            port: 9200
          timeoutSeconds: 10
        resources: {{- toYaml .Values.searchOpensearch.opensearch.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-data
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: opensearch-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources: {{ .Values.searchOpensearch.volumeClaims.opensearchData | toYaml | nindent 8 }}
      storageClassName: {{ .Values.pvc.fileStorage.storageClass | quote }}
