apiVersion: v1
kind: Service
metadata:
  name: haystack-rag-opensearch
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/instance: haystack-rag
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/group: search
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: haystack-rag
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/group: search
  ports:
    - name: rest-api
      port: 9200
      targetPort: 9200
    - name: performance
      port: 9600
      targetPort: 9600

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: haystack-rag-search-opensearch
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/instance: haystack-rag
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/group: search
spec:
  serviceName: haystack-rag-opensearch
  replicas: 1
  selector:
    matchLabels:
      app: haystack-rag
      app.kubernetes.io/component: opensearch
      app.kubernetes.io/group: search
  template:
    metadata:
      labels:
        app: haystack-rag
        app.kubernetes.io/component: opensearch
        app.kubernetes.io/group: search
    spec:
      containers:
      - name: opensearch
        image: "opensearchproject/opensearch:2.11.0"
        imagePullPolicy: IfNotPresent
        env:
          - name: discovery.type
            value: "single-node"
          - name: bootstrap.memory_lock
            value: "false"
          - name: OPENSEARCH_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: OPENSEARCH_SECURITY_ENABLED
            value: "true"
          - name: OPENSEARCH_INITIAL_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: haystack-rag-secrets
                key: opensearch-user
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: haystack-rag-secrets
                key: opensearch-password
        ports:
          - name: rest-api
            containerPort: 9200
          - name: performance
            containerPort: 9600
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "4Gi"
            cpu: "1000m"
            ephemeral-storage: "4Gi"
        volumeMounts:
          - name: opensearch-data
            mountPath: /usr/share/opensearch/data
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
  volumeClaimTemplates:
  - metadata:
      name: opensearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "hostpath"
      resources:
        requests:
          storage: "30Gi"
