apiVersion: v1
kind: Service
metadata:
  name: haystack-rag-query
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/instance: haystack-rag
    app.kubernetes.io/component: query
    app.kubernetes.io/group: backend
spec:
  type: ClusterIP
  selector:
    app: haystack-rag
    app.kubernetes.io/component: query
    app.kubernetes.io/group: backend
  ports:
    - name: query-api
      port: 8002
      targetPort: 8002
