apiVersion: v1
kind: ConfigMap
metadata:
  name: haystack-rag-backend-config
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/instance: haystack-rag
    app.kubernetes.io/group: backend
data:
  PYTHONUNBUFFERED: "1"
  OPENSEARCH_HOST: "https://haystack-rag-opensearch.default.svc.cluster.local:9200"
  GENERATOR: openai
  USE_OPENAI_EMBEDDER: "false"
  TOKENIZERS_PARALLELISM: "false"
  LOG_LEVEL: INFO
  HAYSTACK_LOG_LEVEL: INFO
  INDEX_ON_STARTUP: "true"
