apiVersion: v1
kind: Secret
metadata:
  name: haystack-rag-secrets
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/instance: haystack-rag
type: Opaque
data:
  opensearch-user: YWRtaW4=                 # "admin"
  opensearch-password: eW91ci1wYXNzd29yZC1oZXJl  # "your-password-here"
  openai-api-key: c2stcHJvai05OTk=             # "sk-proj-999"
