apiVersion: v1
kind: Service
metadata:
  name: haystack-rag-opensearch
  labels:
    app.kubernetes.io/name: haystack-rag
    app.kubernetes.io/instance: haystack-rag
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/group: search
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: haystack-rag
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/group: search
  ports:
    - name: rest-api
      port: 9200
      targetPort: 9200
    - name: performance
      port: 9600
      targetPort: 9600
