---
# Source: rag/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haystack-rag-file-storage
  labels:
    app.kubernetes.io/group: backend
    app: haystack-rag
    helm.sh/chart: rag-0.1.0
    app.kubernetes.io/name: rag
    app.kubernetes.io/instance: haystack
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "30Gi"
  storageClassName: "local-path"
